# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt
#--use-mirrors
install: pip install -r requirements-debug.txt

# command to run tests
script: py.test --cov-report html --cov=django-admin-view-permission tests/

# report coverage to coveralls.io
after_success: coveralls